fix: Avoid exceptions when using null values
This fix prevents errors in azure data studio when using null values
in the built-in postgres range types.

For the 'date' range-types (tstzrange, tsrange, daterange) the
following error message is currently displayed in azure data studio:

    Unhandled exception while executing query: 'NoneType' object
    has no attribute 'isoformat'

For the 'numeric' range-types (numrange, int4range, int8range)
the following error:

    Unhandled exception while executing query: int() argument must
    be a string, a bytes-like object or a number, not 'NoneType'

This bug-fix corrects this behavior, so that you get results similar
using psql (PostgreSQL interactive terminal) in the shell.

Additionally, a small refactoring has been done so that the
corresponding formatted value string (variable formatted_value_str)
is generated in a single method only.